apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pznajynq-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-docker-artifactory-jcr.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/pznajynq-go:bc6c05ec18ef6fda0f01a551e4734161d6b7f249@sha256:3b996b0cc64fafe23f12b4560a755749bdf56620dc579fdaeeb6df720ed0ade7
          name: container-image
